services:
  app:
    container_name: algopy_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BACKTEST_BACKEND=vectorbt
    ports:
      - "8501:8501"
      - "8888:8888"
    volumes:
      - .:/app